GET http://localhost:5000

###
POST http://localhost:5000/api/v1/add-income
Content-Type: application/json

{
    "title":"Georgi Haydukov",
    "amount": "45",
    "category": "Salary",
    "description": "My Income",
    "date":"06-01-2023"
}

# ###
# POST http://localhost:3001/todo/new
# Content-Type: application/json

# {
#     "text": "Get a JOB!!!"
# }

# ###
# DELETE http://localhost:3001/todo/delete/647741e8987f022c130933f2

# ### 
# PUT http://localhost:3001/todo/complete/647741e8987f022c130933f2